export const GET_WINNERS = "GET_WINNERS";
export const ADD_TO_SELECTED = "ADD_TO_SELECTED";
export const CLEAR_SELECTED_LIST = "CLEAR_SELECTED_LIST";
export const IS_BINGO = "IS_BINGO";
export const DELETE_WINNING_CONDITION = "DELETE_WINNING_CONDITION";